apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supplier
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: supplier
    spec:
      containers:
      - name: supplier
        image: maryamyumna/supplier:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 10Mi
          limits:
            cpu: 200m
            memory: 100Mi