name: Docker Image CI

on:
  push:
    branches: 
      - main 

jobs:

  setup-build-publish:

    name: Setup build and setup-build-publish
    runs-on: ubuntu-latest

    steps:
    - run: echo "Build started "
    - name: Checkout repository
      uses: actions/checkout@v3
    - run: echo "Project repository has been clonded to runner(ubuntu)"

    #Login to DockerHub

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
